### PR TITLE
Check for invalid (client-side) values during validation

### LINKED ISSUE #369: Validation should fail if any inputs are invalid
#361 introduced client-side validation for numeric inputs. However, an invalid input does not affect the validation of the parent message.

### PR DESCRIPTION
**Pull request by skearnes**
Fixes #369 

New output:

image

### CODE REVIEW

File: editor/js/reaction.js [hunk 1]
```diff
@@ -203,17 +203,26 @@ function addChangeHandler(node, handler) {
...
+ * @param {!Node} node Parent node for the unloaded message.
  * @param {?Node} validateNode Target div for validation output.
  */
-function validate(message, messageTypeString, validateNode) {
+function validate(message, messageTypeString, node, validateNode) {
   // eg message is a type of reaction, messageTypeString = 'Reaction'
   const xhr = new XMLHttpRequest();
   xhr.open('POST', '/dataset/proto/validate/' + messageTypeString);
   const binary = message.serializeBinary();
+  if (!validateNode) {
```
Comment (connorcoley) [inline editor/js/reaction.js:214]: Great move

**Review by connorcoley — APPROVED** [review]
