### PR TITLE
Constrain editable fields for numeric inputs to avoid surprising behavior

### LINKED ISSUE #348: Invalid floats disappear from the pbtxt (and resolve as NaN)
...we should consider factoring out a separate function that checks for NaN and raises and exception on invalid input.

### LINKED ISSUE #360: Handling commas in numbers (esp. when used as decimal points)
Reminder: we had some prior discussion about how to handle commas/periods gracefully. This doesn't have to be changed for this PR, but consider the following:

```
>>> parseFloat('123,456')
123
>>> parseFloat('123.456.789')
123.456
```

Should we silently reject these values? Or should we define a new function `on('change')` for each numerical entry field that will strip commas, raise alerts if invalid, etc.?

_Originally posted by @connorcoley in https://github.com/Open-Reaction-Database/ord-schema/pull/358#discussion_r487422999_

### PR DESCRIPTION
**Pull request by connorcoley**
If we can tell that a string will fail to be parsed correctly into a float when the form is packaged into a proto, we should provide an indication to the user. This effectively adds a handler that is triggered every time a numeric field is changed to only allow characters 0-9, a single decimal point, and a leading hyphen. Other characters (e.g., commas) are simply stripped from the field. Because the user will get real-time feedback about what they've entered, I think this behavior is acceptable. It might seem odd at first though:

- "1.234" -> "1.234"
- "1.234.567" -> "1.234567"
- "123,456.78" -> "123456.78"
- "-0.5apple67" -> "-0.567"
- "5-3" -> "53"
- "1.5" -> 15 (`integertext` fields only, which is just the addition order)

Will close #360
Fixes #348

### CODE REVIEW

File: editor/js/reaction.js [hunk 1]
```diff
@@ -115,7 +115,9 @@ function ready() {
  */
 function listen(node) {
   addChangeHandler($(node), dirty);
-  $('.edittext').on('focus', event => selectText(event.target));
+  $('.edittext', node).on('focus', event => selectText(event.target));
```
Comment (connorcoley) [inline editor/js/reaction.js:118]: Note: this was improperly scoped before so that every time a new element was added to the form, a new onfocus handler was created. This led to >10 of selectText calls to be triggered every time a user clicked on a text field

**Comment by skearnes** [comment]
How would you feel about making all commas errors? I'm worried about our European friends entering things like `1,23` and having that converted to `123` when they really want `1.23`.

I think I'd suggest the same behavior for all non-allowed characters---make them errors rather than stripping them.

**Comment by connorcoley** [comment]
I struggled to figure out how we would display errors there. What does "error" mean to you? Changing the outline of the input field to be red? A javascript pop-up alert? It can't show up as a validation error since those all come from the Python backend after we package up the message.

**Comment by skearnes** [comment]
> I struggled to figure out how we would display errors there. What does "error" mean to you? Changing the outline of the input field to be red? A javascript pop-up alert? It can't show up as a validation error since those all come from the Python backend after we package up the message.

If possible, I think a red outline or warning icon next to the field would be ideal. Something client-side that can be fast. There's a general pattern of "errors creating the proto before we can even validate it" that this fits into...

**Comment by skearnes** [comment]
(Looks like this should also fix #348)

File: editor/js/reaction.js (hunk 1 above)
Comment (skearnes) [reply editor/js/reaction.js:118]: Good catch!

**Comment by connorcoley** [comment]
@skearnes PTAL -- now just adds a 2 px red border to the div that contains the invalid value

**Review by skearnes — APPROVED** [review]
